config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip:[:passwords],controllers: {
    sessions:      'user/sessions',
    registrations: 'user/registrations',
    passwords: 'users/passwords'
  }
  scope module: :user do
    root to: "homes#top"
    get "/about" => "homes#about"
    get 'news/index'
    get "news/data"

    resources :areas,only:[:index,:show,:new]
    resources :contacts, only: [:new, :create]

    resources :toilets,only:[:index,:show,:new,:create,:edit,:update,:destroy] do
      resources :toilet_comments,only:[:create,:destroy]
      resources :toilet_reviews,only:[:create]
      resource :favorites,only:[:create,:destroy]
    end
    resources :buildings,only:[:index,:show,:new,:create,:edit,:update,:destroy] do
      resources :building_comments,only:[:create,:destroy]
      resources :building_reviews,only:[:create]
      resource :building_favorites,only:[:create,:destroy]
    end

    resources :shops,only:[:index,:show,:new,:create,:edit,:update,:destroy] do
      resources :shop_comments,only:[:create,:destroy]
      resources :shop_reviews,only:[:create]
      resource :shop_favorites,only:[:create,:destroy]
    end

    resources :users,only:[:show,:edit,:update]
  end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'user/sessions#guest_sign_in'
  end

  namespace :admin do
    root to: "homes#top"
    resources :areas,only:[:index,:show,:new,:create]
    resources :toilets,only:[:index,:show,:new,:create,:edit,:update,:destroy] do
      resources :toilet_comments,only:[:destroy]
    end
    resources :buildings,only:[:index,:show,:new,:create,:edit,:update,:destroy] do
      resources :building_comments,only:[:destroy]
    end
    resources :shops,only:[:index,:show,:new,:create,:edit,:update,:destroy] do
      resources :shop_comments,only:[:destroy]
    end
  end

  devise_for :admin, skip: [:registrations, :passwords],controllers: {
    sessions: 'admin/sessions'
  }
end

app/models/building.rb
class Building < ApplicationRecord
  belongs_to :area
  belongs_to :user
  has_many :building_comments, dependent: :destroy
  has_many :building_favorites, dependent: :destroy
  has_many :building_reviews, dependent: :destroy

  def favorited_by?(user)
    building_favorites.where(user_id: user.id).exists?
  end

  def avg_score
    unless self.building_reviews.empty?
      building_reviews.average(:score).round(1).to_f
    else
      0.0
    end
  end

  def review_score_percentage
    unless self.building_reviews.empty?
      building_reviews.average(:score).round(1).to_f*100/5
    else
      0.0
    end
  end

  attachment :image
  # N:1

  validates :building_name,presence: true
  validates :introduction,presence: true
  validates :building_name,length: {maximum: 30 }
  validates :introduction,length: {maximum: 100 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :toilet_comments, dependent: :destroy
  has_many :building_comments, dependent: :destroy
  has_many :shop_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :shop_favorites, dependent: :destroy
  has_many :building_favorites, dependent: :destroy
  has_many :toilet_reviews, dependent: :destroy
  has_many :shop_reviews, dependent: :destroy
  has_many :building_reviews, dependent: :destroy
  has_many :toilets, dependent: :destroy
  has_many :buildings, dependent: :destroy
  has_many :shops, dependent: :destroy


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.guest
    find_or_create_by!(email: 'guest@example.com', name: "ゲスト") do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/admin/buildings_controller.rb
class Admin::BuildingsController < ApplicationController
  before_action :authenticate_admin!

  def show
    @building = Building.find(params[:id])
    @building_comment = BuildingComment.new
    @comments = @building.building_comments.order(created_at: :desc)
    @building_review = BuildingReview.new
    @user = User.find(@building.user.id)
    # descを使用してコメント作成順に表示させる
  end

  def edit
    @building = Building.find(params[:id])
  end

  def update
    @building = Building.find(params[:id])
    @building.update(building_params)
    flash[:notice] = '編集が完了しました！'
    redirect_to admin_area_path(@building.area.id)
  end

  def destroy
    @building = Building.find(params[:id])
    @building.destroy
    redirect_to admin_area_path(@building.area.id)
  end


  private
  def building_params
    params.require(:building).permit(:building_name,:introduction,:image,:area_id)
  end
end

app/controllers/user/areas_controller.rb
class User::AreasController < ApplicationController
  def index
    @areas = Area.all
  end

  def show
    @area = Area.find(params[:id])
  end

end

app/controllers/user/building_comments_controller.rb
class User::BuildingCommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]
  def create
    @building = Building.find(params[:building_id])
    @building_comment = BuildingComment.new(building_comment_params)
    @building_comment.user_id = current_user.id
    @building_comment.building_id = @building.id
    @comments = @building.building_comments.order(created_at: :desc)
    @building_comment.save

    flash[:notice] = '投稿が完了しました！'
    # redirect_to toilet_path(@toilet)
    render :index

  end

  def destroy
    @building = Building.find(params[:building_id])
    @building_comment = @building.building_comments.find(params[:id])
    @comments = @building.building_comments.order(created_at: :desc)
    @building_comment.destroy
    # redirect_to toilet_path(@toilet)
    flash[:notice] = '削除が完了しました！'
    render :index

  end

  # def show
  #   @toilet = Toilet.find(params[:id])
  #   @user = User.find(params[:id])
  #   # @toilet_comments = ToiletComments.find(params[:id])
  # end

  def building_comment_params
    params.require(:building_comment).permit(:comment, :image)
  end
end

app/controllers/user/building_favorites_controller.rb
class User::BuildingFavoritesController < ApplicationController
  before_action :authenticate_user!
  def create
    @building = Building.find(params[:building_id])
    @favorite = current_user.building_favorites.new(building_id: @building.id)
    @favorite.save
    # redirect_to shop_path(@shop)
  end

  def destroy
    @building = Building.find(params[:building_id])
    @favorite = current_user.building_favorites.find_by(building_id: @building.id)
    @favorite.destroy
    # redirect_to shop_path(@shop)
  end
end

app/controllers/user/building_reviews_controller.rb
class User::BuildingReviewsController < ApplicationController
  before_action :authenticate_user!
  def create
    @building = Building.find(params[:building_id])
    @building_review = BuildingReview.new(review_params)
    @building_review.user_id = current_user.id
    # @toilet_review.toilet_id = @toilet.id
    @building_review.save
    flash[:notice] = 'レビュー投稿が完了しました！'
    redirect_to area_path(@building.area.id)
  end

  private
  def review_params
    params.require(:building_review).permit(:building_id,:score)
  end
end

app/controllers/user/buildings_controller.rb
class User::BuildingsController < ApplicationController
  before_action :authenticate_user!
  def index
  end

  def show
    @building = Building.find(params[:id])
    @building_comment = BuildingComment.new
    @comments = @building.building_comments.order(created_at: :desc)
    @building_review = BuildingReview.new
    @user = User.find(@building.user.id)
    # descを使用してコメント作成順に表示させる
  end

  def new
    @building = Building.new
    @area = Area.all
  end

  def create
    @building = Building.new(building_params)
    @building.user_id = current_user.id
    if @building.save
      flash[:notice] = '投稿が完了しました！'
    redirect_to area_path(@building.area.id)
    else
    render :new
    end
  end

  def edit
    @building = Building.find(params[:id])
  end

  def update
    @building = Building.find(params[:id])
    @building.update(building_params)
    flash[:notice] = '編集が完了しました！'
    redirect_to areas_path
  end

  def destroy
    building = Building.find(params[:id])
    building.destroy
    redirect_to areas_path
  end

  private
  def building_params
    params.require(:building).permit(:building_name,:introduction,:image,:area_id)
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/contacts_controller.rb
class User::ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end
  
  def create
  @contact = Contact.new(contact_params)
    if @contact.save
    ContactMailer.send_mail(@contact).deliver_now
    flash[:notice] = 'お問い合わせが完了しました！'
    redirect_to root_path
    else
    render :new
    end
  end
  
  private
  def contact_params
    params.require(:contact).permit(:email,:name,:phone_number,:subject,:message)
  end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController
  before_action :authenticate_user!
  def create
    @toilet = Toilet.find(params[:toilet_id])
    @favorite = current_user.favorites.new(toilet_id: @toilet.id)
    @favorite.save
    # redirect_to toilet_path(@toilet)
  end

  def destroy
    @toilet = Toilet.find(params[:toilet_id])
    @favorite = current_user.favorites.find_by(toilet_id: @toilet.id)
    @favorite.destroy
    # redirect_to toilet_path(@toilet)
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/user/news_controller.rb
class User::NewsController < ApplicationController
    def index
    end


    def data
      uri = URI.parse('https://newsapi.org/v2/everything?q=%E3%83%95%E3%83%BC%E3%83%89%E3%83%87%E3%83%AA%E3%83%90%E3%83%AA%E3%83%BC&from=2021-11-15&sortBy=popularity&apiKey=1ea19b6c7e42424f9d05e6bfa818d657')
      json = Net::HTTP.get(uri)
      moments = JSON.parse(json)
      @data = moments['articles'].to_json
    end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  
  before_action :ensure_normal_user, only: :create

  def ensure_normal_user
    if params[:user][:email].downcase == 'guest@example.com'
      redirect_to new_user_session_path, alert: 'ゲストユーザーのパスワード再設定はできません。'
    end
  end
  
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  
  before_action :ensure_normal_user, only: %i[update destroy]
  
  def ensure_normal_user
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーの更新・削除は削除出来ません！！'
    end
  end
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def guest_sign_in
    user = User.guest
    sign_in user
    flash[:notice] = 'ゲストユーザーとしてログインしました。'
    redirect_to root_path
  end
end

app/controllers/user/shop_comments_controller.rb
class User::ShopCommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]
  def create
    @shop = Shop.find(params[:shop_id])
    @shop_comment = ShopComment.new(shop_comment_params)
    @shop_comment.user_id = current_user.id
    @shop_comment.shop_id = @shop.id
    @comments = @shop.shop_comments.order(created_at: :desc)

    @shop_comment.save
    flash[:notice] = '投稿が完了しました！'
    # redirect_to toilet_path(@toilet)
    render :index

  end

  def destroy
    @shop = Shop.find(params[:shop_id])
    @shop_comment = @shop.shop_comments.find(params[:id])
    @comments = @shop.shop_comments.order(created_at: :desc)
    @shop_comment.destroy
    # redirect_to toilet_path(@toilet)
    flash[:notice] = '削除が完了しました！'
    render :index

  end

  # def show
  #   @toilet = Toilet.find(params[:id])
  #   @user = User.find(params[:id])
  #   # @toilet_comments = ToiletComments.find(params[:id])
  # end

  def shop_comment_params
    params.require(:shop_comment).permit(:comment, :image)
  end
end

app/controllers/user/shop_favorites_controller.rb
class User::ShopFavoritesController < ApplicationController
  before_action :authenticate_user!
  def create
    @shop = Shop.find(params[:shop_id])
    @favorite = current_user.shop_favorites.new(shop_id: @shop.id)
    @favorite.save
    # redirect_to shop_path(@shop)
  end

  def destroy
    @shop = Shop.find(params[:shop_id])
    @favorite = current_user.shop_favorites.find_by(shop_id: @shop.id)
    @favorite.destroy
    # redirect_to shop_path(@shop)
  end
end

app/controllers/user/shop_reviews_controller.rb
class User::ShopReviewsController < ApplicationController
  before_action :authenticate_user!

  def create
    @shop = Shop.find(params[:shop_id])
    @shop_review = ShopReview.new(review_params)
    @shop_review.user_id = current_user.id
    # @shop_review.shop_id = @shop.id
    @shop_review.save
    flash[:notice] = 'レビュー投稿が完了しました！'
    redirect_to area_path(@shop.area.id)
  end

  private
  def review_params
    params.require(:shop_review).permit(:shop_id,:score)
  end
end

app/views/user/buildings/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="new-post">
        <%= form_with model: @building, local:true do |f| %>
        <h3>建物編集画面</h3>
        
          <%= f.label :画像, class: "form-label" %><br>
          <%= f.attachment_field :image %><br><br>
          
          <%= f.label :名前名, class: "form-label" %><br>
          <%= f.text_field :building_name, class: "form-control", placeholder: "建物名を入力してください" %><br>
  
          <%= f.label :説明, class: "form-label" %><br>
          <%= f.text_field :introduction, class: "form-control", placeholder: "説明を入力してください"  %><br>
          
          <%= f.label :地域名, class: "form-label" %><br>
          <%= f.collection_select :area_id, Area.all, :id, :area_name, include_blank: "-- 選択してください --" %><br><br>
          <%= f.submit '保存', class: "btn btn-outline-dark" %>
  
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/user/buildings/index.html.erb
<h1>User::Building#index</h1>
<p>Find me in app/views/user/building/index.html.erb</p>

app/views/user/buildings/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="new-post">
        <%= render 'user/toilets/errors' , object:@building %>
        <%= form_with model: @building, local:true do |f| %>
        <h3>建物新規投稿</h3>
        
          <%= f.label :画像, class: "form-label" %><br>
          <%= f.attachment_field :image %><br><br>
          
          <%= f.label :名前名, class: "form-label" %><br>
          <%= f.text_field :building_name, class: "form-control", placeholder: "建物名を入力してください" %><br>
  
          <%= f.label :説明, class: "form-label" %><br>
          <%= f.text_field :introduction, class: "form-control", placeholder: "説明を入力してください"  %><br>
          
          <%= f.label :地域名, class: "form-label" %><br>
          <%= f.collection_select :area_id, Area.all, :id, :area_name, include_blank: "-- 選択してください --" %><br><br>
          <%= f.submit '投稿', class: "btn btn-outline-dark" %>
  
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/user/buildings/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="new-post">
        <%= render 'user/toilets/errors' , object:@building %>
        <h3 style="border-bottom: solid; border-bottom-color: #dcdcdc;">建物詳細ページ</h3>
        <% if @user.id == current_user.id %>
          <div class="edit-button">
            <%= link_to "編集",edit_building_path(@building),class: "btn btn-primary btn-circle m-1" %>
            <%= link_to "削除",building_path(@building),method: :delete ,class: "btn btn-danger btn-circle m-1" %>
          </div>
        <% end %>
        <p id = "favorite_buttons_<%= @building.id %>">
        <%= render 'user/building_favorites/favorite' , building: @building %>
        </p>
        <%= render 'user/building_reviews/form',building: @building, building_review: @building_review %>
          <table class="table table-bordered">
            <thead>
              <tr style="text-align: center;">
                <th>写真</th>
                <th>建物名</th>
                <th>説明</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= attachment_image_tag @shop,:image,format: 'jpeg', fallback: "new_toilet_image.jpg",size: "250x150",class: "image_box" %></td>
                <td><%= @building.building_name %></td>
                <td><%= @building.introduction %></td>
              </tr>
            </tbody>
          </table>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
          <div class="col-12">
            <div class="new-post">
              <div id="comments_area">
                <%= render "user/building_comments/index",comments: @comments %>
              </div>
            <div>
              <%= form_with(model:[@building, @building_comment]) do |f| %>

                <%= f.label :画像, class: "form-label" %><br>
                <%= f.attachment_field :image %><br><br>

                <%= f.label :コメント, class: "form-label" %><br>
                <%= f.text_area :comment, class: "form-control",rows:'3',placeholder: "コメントをここに" %><br>
                <%= f.submit "コメントする" %>
              <% end %>
           </div>
         </div>
        </div>
      </div>
    </div>