config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip:[:passwords],controllers: {
    sessions:      'user/sessions',
    registrations: 'user/registrations',
    passwords: 'users/passwords'
  }
  scope module: :user do
    root to: "homes#top"
    get "/about" => "homes#about"
    get 'news/index'
    get "news/data"

    resources :areas,only:[:index,:show,:new]
    resources :contacts, only: [:new, :create]

    resources :toilets,only:[:index,:show,:new,:create,:edit,:update,:destroy] do
      resources :toilet_comments,only:[:create,:destroy]
      resources :toilet_reviews,only:[:create]
      resource :favorites,only:[:create,:destroy]
    end
    resources :buildings,only:[:index,:show,:new,:create,:edit,:update,:destroy] do
      resources :building_comments,only:[:create,:destroy]
      resources :building_reviews,only:[:create]
      resource :building_favorites,only:[:create,:destroy]
    end

    resources :shops,only:[:index,:show,:new,:create,:edit,:update,:destroy] do
      resources :shop_comments,only:[:create,:destroy]
      resources :shop_reviews,only:[:create]
      resource :shop_favorites,only:[:create,:destroy]
    end

    resources :users,only:[:show,:edit,:update]
  end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'user/sessions#guest_sign_in'
  end

  namespace :admin do
    root to: "homes#top"
    resources :areas,only:[:index,:show,:new,:create]
    resources :toilets,only:[:index,:show,:new,:create,:edit,:update,:destroy] do
      resources :toilet_comments,only:[:destroy]
    end
    resources :buildings,only:[:index,:show,:new,:create,:edit,:update,:destroy] do
      resources :building_comments,only:[:destroy]
    end
    resources :shops,only:[:index,:show,:new,:create,:edit,:update,:destroy] do
      resources :shop_comments,only:[:destroy]
    end
  end

  devise_for :admin, skip: [:registrations, :passwords],controllers: {
    sessions: 'admin/sessions'
  }
end

app/models/toilet.rb
class Toilet < ApplicationRecord
  belongs_to :area
  belongs_to :user
  has_many :toilet_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :toilet_reviews, dependent: :destroy


  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def avg_score
    unless self.toilet_reviews.empty?
      toilet_reviews.average(:score).round(1).to_f
    else
      0.0
    end
  end

  def review_score_percentage
    unless self.toilet_reviews.empty?
      toilet_reviews.average(:score).round(1).to_f*100/5
    else
      0.0
    end
  end

  attachment :image
  # N:1

  validates :toilet_name,presence: true
  validates :introduction,presence: true
  validates :toilet_name,length: {maximum: 30 }
  validates :introduction,length: {maximum: 100 }
end

app/controllers/admin/toilets_controller.rb
class Admin::ToiletsController < ApplicationController
  before_action :authenticate_admin!

  def show
    @toilet = Toilet.find(params[:id])
    @toilet_comment = ToiletComment.new
    @comments = @toilet.toilet_comments.order(created_at: :desc)
    @toilet_review = ToiletReview.new
    @user = User.find(@toilet.user.id)
    # descを使用してコメント作成順に表示させる
  end

  def edit
    @toilet = Toilet.find(params[:id])
  end

  def update
    @toilet = Toilet.find(params[:id])
    @toilet.update(toilet_params)
    flash[:notice] = '編集が完了しました！'
    redirect_to admin_area_path(@toilet.area.id)
  end

  def destroy
    @toilet = Toilet.find(params[:id])
    @toilet.destroy
    redirect_to admin_area_path(@toilet.area.id)
  end


  private
  def toilet_params
    params.require(:toilet).permit(:toilet_name,:introduction,:image,:area_id)
  end
end

app/controllers/user/toilets_controller.rb
class User::ToiletsController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def show
    @toilet = Toilet.find(params[:id])
    @toilet_comment = ToiletComment.new
    @comments = @toilet.toilet_comments.order(created_at: :desc)
    @toilet_review = ToiletReview.new
    @user = User.find(@toilet.user.id)
    # descを使用してコメント作成順に表示させる
  end

  def new
    @toilet = Toilet.new
    @area = Area.all
  end

  def create
    @toilet = Toilet.new(toilet_params)
    @toilet.user_id = current_user.id
    if @toilet.save
      flash[:notice] = '投稿が完了しました！'
      redirect_to area_path(@toilet.area.id)
    else
      render :new
    end
  end

  def edit
    @toilet = Toilet.find(params[:id])
  end

  def update
    @toilet = Toilet.find(params[:id])
    @toilet.update(toilet_params)
    flash[:notice] = '編集が完了しました！'
    redirect_to areas_path
  end

  def destroy
    toilet = Toilet.find(params[:id])
    toilet.destroy
    redirect_to areas_path
  end

  private
  def toilet_params
    params.require(:toilet).permit(:toilet_name,:introduction,:image,:area_id)
  end
end

app/helpers/admin/toilets_helper.rb
module Admin::ToiletsHelper
end

app/helpers/user/toilets_helper.rb
module User::ToiletsHelper
end

app/views/admin/toilets/_errors.html.erb
<% if object.errors.any? %>
   <div id="error_explanation" class="alert alert-danger">
    <ul>
    <%= object.errors.count %>件のエラーが発生しまいます！
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/toilets/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="new-post">
        <%= form_with model: @toilet,url: admin_toilet_path,method: :patch, local:true do |f| %>
        <h3>トイレ編集投稿</h3>
        
          <%= f.label :画像, class: "form-label" %><br>
          <%= f.attachment_field :image %><br><br>
          
          <%= f.label :名前名, class: "form-label" %><br>
          <%= f.text_field :toilet_name, class: "form-control", placeholder: "トイレ名を入力してください" %><br>
  
          <%= f.label :説明, class: "form-label" %><br>
          <%= f.text_field :introduction, class: "form-control", placeholder: "説明を入力してください"  %><br>
          
          <%= f.label :地域名, class: "form-label" %><br>
          <%= f.collection_select :area_id, Area.all, :id, :area_name, include_blank: "-- 選択してください --" %><br><br>
          <%= f.submit '保存', class: "btn btn-outline-dark" %>
  
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/toilets/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="new-post">
        <%= form_with model: @toilet,url: admin_toilets_path,method: :post, local:true do |f| %>
        <h3>トイレ新規投稿</h3>

          <%= f.label :画像, class: "form-label" %><br>
          <%= f.attachment_field :image %><br><br>

          <%= f.label :名前名, class: "form-label" %><br>
          <%= f.text_field :toilet_name, class: "form-control", placeholder: "トイレ名を入力してください" %><br>

          <%= f.label :説明, class: "form-label" %><br>
          <%= f.text_field :introduction, class: "form-control", placeholder: "説明を入力してください"  %><br>
          
          <%= f.label :地域名, class: "form-label" %><br>
          <%= f.collection_select :area_id, Area.all, :id, :area_name, include_blank: "-- 選択してください --" %><br><br>
          <%= f.submit '投稿', class: "btn btn-outline-dark" %>

          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/toilets/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="new-post">
        <h3 style="border-bottom: solid; border-bottom-color: #dcdcdc;">トイレ詳細画面</h3>
          <table class="table table-bordered">
            <thead>
              <tr style="text-align: center;">
                <th>写真</th>
                <th>トイレ名</th>
              <th>説明</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= attachment_image_tag @toilet,:image,format: 'jpeg', fallback: "new_toilet_image.jpg",size: "250x150",class: "image_box" %></td>
                <td><%= @toilet.toilet_name %></td>
                <td><%= @toilet.introduction %></td>
              </tr>
            </tbody>
          </table>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
          <div class="col-12">
            <div class="new-post">
              <div id="comments_area">
                <%= render "admin/toilet_comments/index",comments: @comments %>
              </div>
            </div>
          </div>
      </div>
    </div>